import json
import random
import os


QUESTION_REAL = "<video>\n" * 2 + "You have been shown two different videos. One of the videos is generated by AI. Which of the above videos is most likely not generated by AI?"

QUESTION_FAKE = "<video>\n" * 2 + "You have been shown two different videos. One of the videos is not generated by AI. Which of the above videos is most likely generated by AI?"

OPTIONS = ["The first one.", "The second one.", "The third one.", "The fourth one."]

OPTION_LETTERS = ["A", "B", "C", "D"]

def load_data(json_file):
    with open(json_file, 'r') as file:
        data = json.load(file)
    return data


def generate_questions2(data, num_questions=200):
    questions = []
    questions_for_human = []
    
    for sample in data:
        real_video_path = [sample['real_video_path'], sample['fake_video_path']]
        random.shuffle(real_video_path)
        real_answer = "A" if real_video_path[0] == sample['real_video_path'] else "B"
        
        fake_video_path = [sample['real_video_path'], sample['fake_video_path']]
        random.shuffle(fake_video_path)
        fake_answer = "A" if fake_video_path[0] == sample['fake_video_path'] else "B"
        
        model = sample["type"]
        
        real_sample = {"video_path": real_video_path, "question": QUESTION_REAL, "answer": real_answer, 'modality': 'video-text', 'metric': 'multi-choice', 'question_type': f'video_real_from_fake_{model}_multi_choice', 'choices': OPTIONS[:2]}
        fake_sample = {"video_path": fake_video_path, "question": QUESTION_FAKE, "answer": fake_answer, 'modality': 'video-text', 'metric': 'multi-choice', 'question_type': f'video_fake_from_real_{model}_multi_choice', 'choices': OPTIONS[:2]}
        
        questions.append(real_sample)
        questions.append(fake_sample)
        
        question_for_human = {"video_path": [video.replace("/mnt/hwfile/opendatalab/bigdata_rs/datasets/Synthbench/", "") for video in fake_video_path], "question_type": "multi", "type_sec": model, "answer": fake_answer}
        questions_for_human.append(question_for_human)
    
    return questions, questions_for_human
    

def generate_questions(data, num_questions=200):
    real_videos = [video for video in data if not video['is_fake']]
    fake_videos = [video for video in data if video['is_fake']]

    questions_real = []
    questions_fake = []

    for _ in range(num_questions):
        choices_real = random.sample(real_videos, 1) + random.sample(fake_videos, 1)
        random.shuffle(choices_real)
        correct_answer_real = next(i for i, v in enumerate(choices_real) if v['is_fake'])

        choices_fake = random.sample(fake_videos, 1) + random.sample(real_videos, 1)
        random.shuffle(choices_fake)
        correct_answer_fake = next(i for i, v in enumerate(choices_fake) if not v['is_fake'])

        questions_real.append({'video_path': [v['video_path'] for v in choices_real], 'question': QUESTION_REAL, 'answer': OPTION_LETTERS[correct_answer_real], 'modality': 'video-text', 'metric': 'multi-choice', 'question_type': 'fake_from_real_multi_choice', 'choices': OPTIONS[:2]})
        questions_fake.append({'video_path': [v['video_path'] for v in choices_fake], 'question': QUESTION_FAKE, 'answer': OPTION_LETTERS[correct_answer_fake], 'modality': 'video-text', 'metric': 'multi-choice', 'question_type': 'real_from_fake_multi_choice', 'choices': OPTIONS[:2]})

    return questions_real, questions_fake

# 示例路径
json_file_path = '/mnt/petrelfs/zhoubaichuan/projects/synthbench/data/synthbench_video_paired_up_meta.json'
data = load_data(json_file_path)
questions, questions_for_human = generate_questions2(data, num_questions=len(data))


json.dump(questions, open(os.path.join('/mnt/petrelfs/zhoubaichuan/projects/synthbench/data', 'synthbench_video_multi_choice.json'), 'w'), indent=4)

json.dump(questions_for_human, open(os.path.join('/mnt/petrelfs/zhoubaichuan/projects/synthbench/data', 'video_multi_choice_for_human.json'), 'w'), indent=4)

# 打印一些生成的问题
print(len(questions))
print(len(questions_for_human))
