import json
import random
import os


QUESTION = "<video>\n" + "You have been shown one video, possibly generated by AI. \nPlease identify whether this video is generated by AI or not. \nAnswer yes or no first. Then, if you think the video is generated by AI, state your reasons.\n"


OPTIONS = ["The first one.", "The second one.", "The third one.", "The fourth one."]

OPTION_LETTERS = ["A", "B", "C", "D"]

def load_data(json_file):
    with open(json_file, 'r') as file:
        data = json.load(file)
    return data

def generate_questions(data, num_questions=200):
    real_videos = [video for video in data if not video['is_fake']]
    fake_videos = [video for video in data if video['is_fake']]

    questions_real = []
    questions_fake = []
    
    sampled_real_videos = random.sample(real_videos, num_questions)
    sampled_fake_videos = random.sample(fake_videos, num_questions)

    for i in range(num_questions):
        real_sample = sampled_real_videos[i]
        fake_sample = sampled_fake_videos[i]

        questions_real.append({'video_path': real_sample['video_path'], 'question': QUESTION, 'answer': 'No', 'modality': 'video-text', 'metric': 'open-ended', 'question_type': 'fake_or_real_open_ended', 'choices': []})
        questions_fake.append({'video_path': fake_sample['video_path'], 'question': QUESTION, 'answer': 'Yes', 'modality': 'video-text', 'metric': 'open-ended', 'question_type': 'fake_or_real_open_ended', 'choices': []})

    return questions_real, questions_fake

# 示例路径
json_file_path = '/mnt/petrelfs/zhoubaichuan/projects/synthbench/data/synthbench_video_meta.json'
data = load_data(json_file_path)
questions_real, questions_fake = generate_questions(data)

data_list = questions_real + questions_fake

json.dump(data_list, open(os.path.join('/mnt/petrelfs/zhoubaichuan/projects/synthbench/data', 'synthbench_video_true_or_false.json'), 'w'), indent=4)

# 打印一些生成的问题
print("Sample real video question:", questions_real[:3])
print("Sample fake video question:", questions_fake[:3])
