from lm_evaluate.models.llava_next_video_hf import LLaVANeXTVideoHF
from lm_evaluate.models.gpt import GPT
from lm_evaluate.models.xcomposer2d5 import XComposer2D5
from lm_evaluate.models.internvl2 import InternVL2
from lm_evaluate.models.mplug_owl import MPlugOwl
from lm_evaluate.models.vila import VILA
from lm_evaluate.models.minicpm_2_6 import MiniCPM
from lm_evaluate.models.gemini import Gemini
from lm_evaluate.models.longva import LongVA
from lm_evaluate.models.phi3_5_vision import Phi3_5Vision
from lm_evaluate.models.llava_next import LLaVANeXT
from lm_evaluate.models.mantis import Mantis
from lm_evaluate.models.idefics import Idefics